### ISSUE TITLE
[4.0.0-beta.12] @ionic/core not installed during npm install

### ISSUE THREAD

**Issue by iAmAnkeeta** [ionic-team/ionic#15777]
# Bug Report

**Ionic Info**
```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/Users/username/.nvm/versions/node/v8.11.4/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.12
   @angular-devkit/core       : 0.8.3
   @angular-devkit/schematics : 0.8.3
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/username/Library/Android/sdk/)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.11.4 (/Users/username/.nvm/versions/node/v8.11.4/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

```

**Describe the Bug**
@ionic/core is not installed after upgrading @ionic/angular to 4.0.0-beta.12

**Steps to Reproduce**
1. For clean install, remove the node_module folder,
2. Ran `npm install` to install the packages
3. Ran `ionic build` to check for the compilation error

**Error Displayed**
```
src/app/services/action-sheet/action-sheet.service.ts(2,55): error TS2307: Cannot find module '@ionic/core'.
src/app/services/action-sheet/action-sheet.service.ts(35,30): error TS2339: Property 'text' does not exist on type 'IActionSheetButtonOption'.
src/app/services/action-sheet/action-sheet.service.ts(41,26): error TS2339: Property 'role' does not exist on type 'IActionSheetButtonOption'.
src/app/services/action-sheet/action-sheet.service.ts(41,62): error TS2339: Property 'role' does not exist on type 'IActionSheetButtonOption'.
src/app/services/action-sheet/action-sheet.service.ts(42,26): error TS2339: Property 'icon' does not exist on type 'IActionSheetButtonOption'.
src/app/services/action-sheet/action-sheet.service.ts(42,62): error TS2339: Property 'icon' does not exist on type 'IActionSheetButtonOption'.
src/app/services/action-sheet/action-sheet.service.ts(43,26): error TS2339: Property 'cssClass' does not exist on type 'IActionSheetButtonOption'.
src/app/services/action-sheet/action-sheet.service.ts(43,49): error TS2339: Property 'cssClass' does not exist on type 'IActionSheetButtonOption'.
src/app/services/action-sheet/action-sheet.service.ts(43,73): error TS2339: Property 'cssClass' does not exist on type 'IActionSheetButtonOption'.
src/app/services/alert/alert.service.ts(2,30): error TS2307: Cannot find module '@ionic/core'.
```
Check the node-module folder and saw that core folder didn't exist in @ionic folder
![screen shot 2018-09-27 at 4 57 12 pm](https://user-images.githubusercontent.com/18538734/46174277-936b1c80-c276-11e8-8b96-55629ce1527d.png)

**Comment by manucorporat** [comment]
Remove node_modules and run `npm install` again, i can't reproduce it.

If the issue persist could you provide a repo that reproduces the issue?

**Comment by iAmAnkeeta** [comment]
Thank you, @manucorporat!

Yesterday, I did that and still was having the same issue, i rolled back to ionic/cli 4.1.0, the @ionic/core was installed.
This morning I reinstalled the cli to 4.1.2 and removed the node_module and ran npm install again. Now I see core folder.

**Comment by brandyscarney** [comment]
I'm going to close this since it seems you got it working, but let us know if you're still having the issue. Thanks!
