### ISSUE TITLE
[4.0.0-beta.16] ionic can not run on stackblitz

### ISSUE THREAD

**Issue by comfortme** [ionic-team/ionic#16354]
# Bug Report

**Ionic Info**
```
ionic/angular 4.0.0-beta.16
```

**Describe the Bug**
an ionic 4 beta16 project can not run on stackblitz

**Steps to Reproduce**
1. visit https://stackblitz.com/edit/beta16
2. see `require.context is not a function` error

**Expected Behavior**
ionic should run on stackblitz

**Additional Context**
projects can run until beta7. even then icons are not showing. 
see https://github.com/ionic-team/ionic/issues/15456

**Comment by comfortme** [comment]
this issue still exists in beta 18
https://stackblitz.com/edit/beta18

**Comment by ptitjes** [comment]
The error is different with 4.0.0-beta.19 now:
```
Import error, can't find files:
./ios-add-circle-outline.svg
./ios-add-circle.svg
./ios-add.svg
./ios-airplane.svg
./ios-alarm.svg
./ios-albums.svg
./ios-alert.svg
./ios-american-football.svg
...
```
C.f. https://stackblitz.com/edit/angular-ionic-v4-alignment-toolbar-buttons

It would be great if this could work for the next betas as it is easier to convey code with StackBlitz for bug reports rather than creating a whole GitHub project for each and every issue.

**Comment by comfortme** [comment]
@ptitjes 
same error with rc0 also

**Comment by ovimughal** [comment]
Tried `ionic-conference-app`, still not working.

**Comment by comfortme** [comment]
still no good with rc.1

**Comment by Frotty** [comment]
Yup, subscribing to this. Ionicons seem to error, even changing angular.json as described in changelog has no effect https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

**Comment by comfortme** [comment]
not working with rc.2 either. https://stackblitz.com/edit/rc2

**Comment by ryaa** [comment]
still not working with the latest build 4.0.1

**Comment by comfortme** [comment]
yes the error is different in every version though. 
With 4.01, there are many `System.registerDynamic dependency `errors. one of them is below.
```

ERROR
Error: Uncaught (in promise): Error: Module ./build/sjcqnbtt.entry.js not declared as a System.registerDynamic dependency of https://rc2.stackblitz.io/turbo_modules/@ionic/core@4.0.1/dist/esm/es5/ionic.core.js
Error: Module ./build/sjcqnbtt.entry.js not declared as a System.registerDynamic dependency of https://rc2.stackblitz.io/turbo_modules/@ionic/core@4.0.1/dist/esm/es5/ionic.core.js
at https://c.staticblitz.com/d/webcontainer.763626ae3b49f0b26e9.js:15:13318
at eval (https://rc2.stackblitz.io/turbo_modules/@ionic/core@4.0.1/dist/esm/es5/ionic.core.js:65:93)
at ZoneDelegate.invoke (https://rc2.stackblitz.io/turbo_modules/zone.js@0.8.29/dist/zone.js:391:26)
at Object.onInvoke (https://rc2.stackblitz.io/turbo_modules/@angular/core@7.2.4/bundles/core.umd.js:17333:37)
at ZoneDelegate.invoke (https://rc2.stackblitz.io/turbo_modules/zone.js@0.8.29/dist/zone.js:390:52)
at Zone.run (https://rc2.stackblitz.io/turbo_modules/zone.js@0.8.29/dist/zone.js:150:43)
at eval (https://rc2.stackblitz.io/turbo_modules/zone.js@0.8.29/dist/zone.js:889:34)
at ZoneDelegate.invokeTask (https://rc2.stackblitz.io/turbo_modules/zone.js@0.8.29/dist/zone.js:423:31)
at Object.onInvokeTask (https://rc2.stackblitz.io/turbo_modules/@angular/core@7.2.4/bundles/core.umd.js:17324:37)
at ZoneDelegate.invokeTask (https://rc2.stackblitz.io/turbo_modules/zone.js@0.8.29/dist/zone.js:422:60)
```

**Comment by brandyscarney** [comment]
Just to update this issue we are working directly with Stackblitz to get Ionic 4 working with it. We're currently blocked by https://github.com/stackblitz/core/issues/72 but we have brought it to their attention.

Thanks for the patience!

**Comment by brandyscarney** [comment]
We currently have this working, it should be in the `4.7.0` release! Will get an example link added once that is out. Related PR: https://github.com/ionic-team/ionic/pull/18846

**Comment by brandyscarney** [comment]
Ionic is now working on Stackblitz as of `4.7.0`! Here's an example: https://stackblitz.com/edit/ionic-v4-angular-tabs

We will update the issue templates to include links for Stackblitz in order to use it to reproduce issues. :blue_heart:
