### ISSUE TITLE
Cannot find module './swiper/swiper-interfaces' after 3.5.3 update

### ISSUE THREAD

**Issue by KrunchMuffin** [ionic-team/ionic#12450]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

after upgrade from 3.5.0 to 3.5.3 and running `ionic lab` I get the error listed below.

**Expected behavior:**

transpile w/o error 

**Steps to reproduce:**
upgrade and do `ionic lab`

**Related code:**

```
insert any relevant code here
```

**Other information:**

``` [02:18:00]  typescript: ...rek/Documents/firstapp2/node_modules/ionic-angular/components/slides/slides.d.ts, line: 5
  Cannot find module './swiper/swiper-interfaces'.
   L4:  import { Platform } from '../../platform/platform';
   L5:  SlideContainer, SlideElement, SlideTouchEvents, SlideTouches, SlideZoom } from './swiper/swiper-interfaces';
   L6:  import { ViewController } from '../../navigation/view-controller';
```

**Ionic info:**

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v8.1.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind updating to the latest release of `npm` (npm install -g npm), remove your node_modules and package-lock file and then do a fresh npm install and see if you get the same error please?

**Comment by KrunchMuffin** [comment]
Well, it fixed that error, but generated a new one.

```
[12:50:01]  typescript: C:/Users/Derek/Documents/firstapp2/node_modules/rxjs/Subject.d.ts, line: 16
            Class 'Subject<T>' incorrectly extends base class 'Observable<T>'. Types of property 'lift' are
            incompatible. Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator:
            Operator<T, R>) => Observable<R>'. Type 'Observable<T>' is not assignable to type 'Observable<R>'. Type 'T'
            is not assignable to type 'R'.

      L16:  export declare class Subject<T> extends Observable<T> implements ISubscription {
      L17:      observers: Observer<T>[];
```

**Comment by KrunchMuffin** [comment]
I noticed my rxjs  was  at 5.4.0 and latest is 5.4.2, so I upgraded it that error went away, although I get this warning.

> npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
>npm WARN ionic-angular@3.5.3 requires a peer of rxjs@5.4.0 but none was installed.

**Comment by jgw96** [comment]
@KrunchMuffin hmmm, could you post your package.json, please?

**Comment by KrunchMuffin** [comment]
```
{
    "name": "app",
    "version": "0.0.1",
    "author": "me",
    "homepage": "",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/device": "^3.14.0",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/cloud-angular": "^0.12.0",
        "@ionic/storage": "^2.0.1",
        "angular2-jwt": "^0.2.3",
        "cordova-android": "^6.2.3",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.5.3",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "^5.4.2",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.0.0",
        "@ionic/cli-plugin-cordova": "1.4.1",
        "@ionic/cli-plugin-ionic-angular": "1.3.2",
        "typescript": "^2.3.4"
    },
    "description": "App for ",
    "cordova": {
        "plugins": {
            "cordova-plugin-device": {},
            "cordova-plugin-console": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {}
        },
        "platforms": [
            "android"
        ]
    }
}

```

**Comment by jgw96** [comment]
Ahh, would you mind updating your app-scripts to `2.0.2` ? `npm install @ionic/app-scripts@2.0.2 --save-dev`

**Comment by KrunchMuffin** [comment]
I tried that last week and all hell broke loose. I can try again.

**Comment by jgw96** [comment]
@KrunchMuffin let me know when you get a chance to give this a try (:

**Comment by KrunchMuffin** [comment]
I just did, got a bunch of warnings.

```
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN ionic-angular@3.5.3 requires a peer of rxjs@5.4.0 but none was installed.
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Comment by jgw96** [comment]
@KrunchMuffin is it possible for you to share this repo your having issues with?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
