### ISSUE TITLE
Updating to 3.8.0 error

### ISSUE THREAD

**Issue by butavpaul** [ionic-team/ionic#13273]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

After updating to 3.8.0 I can't use ionic server to my project. Each time I get different error, like
this, after I delete node_platforms and install again the scripts.
"Cannot find module '@angular/tsc-wrapped/src/tsc'" or
Cannot find module 'typescript' and others.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.4.0
    npm  : 5.4.2 
    OS   : macOS Sierra

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by butavpaul** [comment]
Solved by removing android platform and add it again but now I have this error.
![screen-shot-2017-10-29-at-2 18 32-am](https://user-images.githubusercontent.com/8864497/32139400-e557cf26-bc4f-11e7-9d4d-4277286cc0ab.png)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us! Would you be able to provide a sample application via GitHub that demonstrates the issue you are having? Thanks for using Ionic!

**Comment by pwespi** [comment]
Are you using ionic2-super-tabs? If yes, then the error is likely caused by that module. See https://github.com/zyra/ionic2-super-tabs/issues/203.
