### ISSUE TITLE
bug: core.js:6228 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError

### ISSUE THREAD

**Issue by conde2** [ionic-team/ionic#21489]
# Bug Report

**Ionic version:**

[x] **5.2**

**Current behavior:**
Whenever entering a page with some components like 

- ion-radio-group 
- ion-range 
- ion-searchbar

I got this error:

![Captura de tela de 2020-06-10 18-42-55](https://user-images.githubusercontent.com/2137569/84322447-65f9fb80-ab4b-11ea-8e0e-9b78c42709a6.png)

**Expected behavior:**
Not have any error.

**Steps to reproduce:**
Just update to latest ionic and angular and insert this snippet anywhere

**Related code:**

```
<ion-content >
  <ion-radio-group></ion-radio-group>
</ion-content>
```

**Other information:**
After updating to new ionic and angular I started getting this error.

![Captura de tela de 2020-06-10 18-52-51](https://user-images.githubusercontent.com/2137569/84322636-afe2e180-ab4b-11ea-84d9-21bc80d16475.png)

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.9.2 (/usr/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.0
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v14.2.0 (/usr/bin/node)
   npm    : 6.14.5
   OS     : Linux 5.6
```

**Comment by netsesame2** [comment]
The same issue here.

**Comment by ZhipengZeng** [comment]
I have the same issue with ion-segment in the page.
Turns out in ionic 5.2 it requires [(ngModel)] present.

in my case:
from:

```
<ion-segment (ionChange)="segmentChanged($event)" value="init">
  <ion-segment-button value="init">
    <ion-label>Init</ion-label>
  </ion-segment-button>
  <ion-segment-button value="using">
    <ion-label>Using</ion-label>
  </ion-segment-button>
</ion-segment>
```

to:
```
<ion-segment (ionChange)="segmentChanged($event)" [(ngModel)]="currentValue">
  <ion-segment-button value="init">
    <ion-label>Init</ion-label>
  </ion-segment-button>
  <ion-segment-button value="using">
    <ion-label>Using</ion-label>
  </ion-segment-button>
</ion-segment>
```

**Comment by abuassar** [comment]
This is not mentioned in the changelog

As it contains no breaking changes.

في خميس، 11 يونيو، 2020 في 4:10 ص، كتب Zhipeng Zeng <
notifications@github.com>:

**Comment by bleuscyther** [comment]
Omg! it feels so good to finally see a way to fix the error! @ZhipengZeng

**Comment by netsesame2** [comment]
I have a ng-toggle added in app.component.html.
<ion-toggle slot="end" [checked]="darkMode" [ngModal]="darkMode"></ion-toggle>

It will raise above errors whatever I add ngModal or not.

**Comment by KillerCodeMonkey** [comment]
> I have a ion-toggle component added in app.component.html.
> <ion-toggle slot="end" [checked]="darkMode" [ngModal]="darkMode">
> 
> It will raise above errors whatever I add ngModal or not.
> Downgrade to 5.1.1, expect to be resolved.

because it is `ngModel` and not `ngModal` @netsesame2

**Comment by netsesame2** [comment]
> > I have a ion-toggle component added in app.component.html.
> > <ion-toggle slot="end" [checked]="darkMode" [ngModal]="darkMode">
> > It will raise above errors whatever I add ngModal or not.
> > Downgrade to 5.1.1, expect to be resolved.
> 
> because it is `ngModel` and not `ngModal` @netsesame2

Sorry for my mistake, change to ngModel, and still raise error.

**Comment by ionic4themes** [comment]
After migrating from v4 to v5, I have a similar issue with **ion-input**. I get a "white screen" and the following console error (with ng serve):

`core.js:4117 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(SigninPageModule)[NgControl -> NgControl -> NgControl -> NgControl]: 
  NullInjectorError: No provider for NgControl!
NullInjectorError: R3InjectorError(SigninPageModule)[NgControl -> NgControl -> NgControl -> NgControl]: 
  NullInjectorError: No provider for NgControl!`

my Ionic Info:

`Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\jose_\AppData\Roaming\nvm\v10.16.2\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.2.0
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.9.0) : 0.8.1
   native-run (update available: 0.3.0)  : 0.2.9

System:

   NodeJS : v10.16.2 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10`

and package.json content:

`    "@angular/common": "~9.1.11",
    "@angular/compiler": "~9.1.11",
    "@angular/core": "~9.1.11",
    "@angular/forms": "~9.1.11",
    "@angular/platform-browser": "~9.1.11",
    "@angular/platform-browser-dynamic": "~9.1.11",
    "@angular/router": "~9.1.11",
    "@ionic-native/core": "^5.26.0",
    "@ionic-native/splash-screen": "^5.26.0",
    "@ionic-native/status-bar": "^5.26.0",
    "@ionic/angular": "^5.2.0",
    "cordova-android": "7.1.4",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.5",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"`

**Comment by UTSOURCE** [comment]
需要添加 [(ngModel)]="对象"

**Comment by copaste** [comment]
I came here to report this as well, the solution is to use [ngModel], it is really strange that that's not mentioned in the changelog as it obviously is a breaking change.

**Comment by ionic4themes** [comment]
> After migrating from v4 to v5, I have a similar issue with **ion-input**. I get a "white screen" and the following console error (with ng serve):
> 
> `core.js:4117 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(SigninPageModule)[NgControl -> NgControl -> NgControl -> NgControl]: NullInjectorError: No provider for NgControl! NullInjectorError: R3InjectorError(SigninPageModule)[NgControl -> NgControl -> NgControl -> NgControl]: NullInjectorError: No provider for NgControl!`
> 
> The HTML code:
> 
> ` <ion-item> <ion-label>Default Label</ion-label> <ion-input></ion-input> </ion-item>`
> 
> my Ionic Info:
> 
> `Ionic:
> 
> Ionic CLI : 5.4.16 (C:\Users\jose_\AppData\Roaming\nvm\v10.16.2\node_modules\ionic)
> Ionic Framework : @ionic/angular 5.2.0
> @angular-devkit/build-angular : 0.901.8
> @angular-devkit/schematics : 9.1.8
> @angular/cli : 9.1.8
> @ionic/angular-toolkit : 2.0.0
> 
> Cordova:
> 
> Cordova CLI : 9.0.0 (cordova-lib@9.0.1)
> Cordova Platforms : not available
> Cordova Plugins : not available
> 
> Utility:
> 
> cordova-res (update available: 0.9.0) : 0.8.1
> native-run (update available: 0.3.0) : 0.2.9
> 
> System:
> 
> NodeJS : v10.16.2 (C:\Program Files\nodejs\node.exe)
> npm : 6.9.0
> OS : Windows 10`
> 
> and package.json content:
> 
> ` "@angular/common": "~9.1.11", "@angular/compiler": "~9.1.11", "@angular/core": "~9.1.11", "@angular/forms": "~9.1.11", "@angular/platform-browser": "~9.1.11", "@angular/platform-browser-dynamic": "~9.1.11", "@angular/router": "~9.1.11", "@ionic-native/core": "^5.26.0", "@ionic-native/splash-screen": "^5.26.0", "@ionic-native/status-bar": "^5.26.0", "@ionic/angular": "^5.2.0", "cordova-android": "7.1.4", "core-js": "^2.5.4", "rxjs": "~6.5.5", "tslib": "^1.10.0", "zone.js": "~0.10.2"`

Solved by adding [ngModel], the point is that we are using the component <ion-input> as a simple "preview component" with no backend, so we had to add a var into .ts and add [ngModel], as @copaste said, this is a breaking change, actually the official documentation is wrong, examples would not work:

![image](https://user-images.githubusercontent.com/44522836/84377708-59c17d00-abe3-11ea-8b00-4c15b2835b1b.png)

**Comment by abuassar** [comment]
@ionic4themes I believe this is unintended change.

**Comment by liamdebeasi** [comment]
Thanks for the issue. We are looking into this.

**Comment by liamdebeasi** [comment]
Can everyone try the following dev build, and let me know if it resolves the issue?

`npm i @ionic/angular@5.3.0-dev.202006111355.b37c158`

This was an unintended bug in the latest 5.2.0 release. Once the fix is verified, we will get a patch release out.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21504, and a fix is now available as part of the Ionic Framework 5.2.1 release. Please update to v5.2.1 in order to receive this bug fix:

```
npm install @ionic/angular@latest
```

This bug was caused by https://github.com/ionic-team/ionic/commit/e95b481a53191582bca635f322ad07eadbd62d64. When attempting to get an `NgControl` on a component, Angular threw an error for components that were not part of a form/did not have `ngModel`. 

The fix for this involves checking to see if the component in question is part of a form/has an `ngModel` to avoid this error.

Apologies for any inconvenience this may have caused. Thanks for using Ionic!

**Comment by KillerCodeMonkey** [comment]
nice and thanks for the fast fix :). I wanted to create a PR this evening, but you were faster :D.

**Comment by abuassar** [comment]
wow that was fast, thanks @liamdebeasi

**Comment by gersonbarbosa7** [comment]
> I have the same issue with ion-segment in the page.
> Turns out in ionic 5.2 it requires [(ngModel)] present.
> 
> in my case:
> from:
> 
> ```
> <ion-segment (ionChange)="segmentChanged($event)" value="init">
>   <ion-segment-button value="init">
>     <ion-label>Init</ion-label>
>   </ion-segment-button>
>   <ion-segment-button value="using">
>     <ion-label>Using</ion-label>
>   </ion-segment-button>
> </ion-segment>
> ```
> 
> to:
> 
> ```
> <ion-segment (ionChange)="segmentChanged($event)" [(ngModel)]="currentValue">
>   <ion-segment-button value="init">
>     <ion-label>Init</ion-label>
>   </ion-segment-button>
>   <ion-segment-button value="using">
>     <ion-label>Using</ion-label>
>   </ion-segment-button>
> </ion-segment>
> ```

It's truth! It works! Thank so much @ZhipengZeng
