### ISSUE TITLE
ionic 4 not work in android 5 and 4.4

### ISSUE THREAD

**Issue by shomid** [ionic-team/ionic#16362]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
Ionic:

   ionic (Ionic CLI)             : 4.3.1
   Ionic Framework               : @ionic/angular 4.0.0-beta.16
   @angular-devkit/build-angular : 0.10.6
   @angular-devkit/schematics    : 7.0.6
   @angular/cli                  : 7.0.6
   @ionic/angular-toolkit        : 1.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1 (/home/omid/programming_tools/android-sdk)
   NodeJS            : v10.13.0 (/usr/bin/node)
   npm               : 6.4.1
   OS                : Linux 4.18

```

**Describe the Bug**
output apk ionic 4 not work in android 4.4 and 5.
when run app in android 4.4 or 5 show blank screen and throw errors following:

`
The key "viewport-fit" is not recognized and ignored. localhost/:9
Uncaught TypeError: Property '__zone_symbol__then' of object [object Promise] is not a function zone.js:240
Uncaught TypeError: pre,template,textarea,script,style is not iterable! _for-of.js:14
`

package.json : 

```
{
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~7.0.3",
    "@angular/core": "~7.0.3",
    "@angular/forms": "~7.0.3",
    "@angular/http": "~7.0.3",
    "@angular/platform-browser": "~7.0.3",
    "@angular/platform-browser-dynamic": "~7.0.3",
    "@angular/router": "~7.0.3",
    "@ionic-native/android-permissions": "^5.0.0-beta.21",
    "@ionic-native/background-geolocation": "^5.0.0-beta.21",
    "@ionic-native/core": "^5.0.0-beta.21",
    "@ionic-native/deeplinks": "^5.0.0-beta.21",
    "@ionic-native/device": "5.0.0-beta.21",
    "@ionic-native/diagnostic": "5.0.0-beta.21",
    "@ionic-native/file": "5.0.0-beta.21",
    "@ionic-native/file-opener": "5.0.0-beta.21",
    "@ionic-native/file-transfer": "5.0.0-beta.21",
    "@ionic-native/geolocation": "5.0.0-beta.21",
    "@ionic-native/google-maps": "^5.0.0-beta.24",
    "@ionic-native/location-accuracy": "5.0.0-beta.21",
    "@ionic-native/network": "5.0.0-beta.21",
    "@ionic-native/social-sharing": "5.0.0-beta.21",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-beta.16",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@stencil/core": "0.15.2",
    "com.lampa.startapp": "^6.1.6",
    "cordova": "^8.1.2",
    "cordova-android": "7.1.2",
    "cordova-browser": "5.0.4",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-opener2": "^2.0.19",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-googlemaps": "2.4.6",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "2.2.3",
    "cordova-plugin-mauron85-background-geolocation": "3.0.0-alpha.47",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-request-location-accuracy": "^2.2.3",
    "cordova-plugin-sms-receive": "^1.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.4.1",
    "cordova.plugins.diagnostic": "^4.0.10",
    "core-js": "^2.5.7",
    "es6-promise-plugin": "^4.2.2",
    "ionic": "^4.3.1",
    "ionic-plugin-deeplinks": "1.0.17",
    "ionicons": "4.4.7",
    "lodash": "4.17.11",
    "moment": "2.22.2",
    "moment-jalaali": "0.8.1",
    "parse-push-plugin": "git+https://github.com/taivo/parse-push-plugin.git",
    "rxjs": "6.3.3",
    "rxjs-compat": "^6.3.3",
    "ws": "^6.1.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.10.5",
    "@angular-devkit/build-angular": "~0.10.5",
    "@angular-devkit/core": "~7.0.5",
    "@angular-devkit/schematics": "~7.0.5",
    "@angular/cli": "~7.0.3",
    "@angular/compiler": "~7.0.3",
    "@angular/compiler-cli": "~7.0.3",
    "@angular/language-service": "~7.0.3",
    "@ionic/angular-toolkit": "^1.2.0",
    "@ionic/lab": "1.0.13",
    "@types/jasmine": "~3.0.0",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~10.12.9",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  },
  "description": "app project",
  "cordova": {
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file-opener2": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-sms-receive": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-x-socialsharing": {},
      "cordova.plugins.diagnostic": {},
      "cordova-plugin-request-location-accuracy": {},
      "cordova-plugin-android-permissions": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-googlemaps": {
        "API_KEY_FOR_ANDROID": "****************",
        "API_KEY_FOR_IOS": "***********************"
      },
      "cordova-plugin-mauron85-background-geolocation": {
        "GOOGLE_PLAY_SERVICES_VERSION": "11+",
        "ANDROID_SUPPORT_LIBRARY_VERSION": "26+",
        "ICON": "@mipmap/icon",
        "SMALL_ICON": "@mipmap/icon",
        "ACCOUNT_NAME": "@string/app_name",
        "ACCOUNT_LABEL": "@string/app_name",
        "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
        "CONTENT_AUTHORITY": "$PACKAGE_NAME"
      },
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "com.lampa.startapp": {},
      "ionic-plugin-deeplinks": {
        "URL_SCHEME": "#######",
        "DEEPLINK_SCHEME": "http",
        "DEEPLINK_HOST": "#####",
        "ANDROID_PATH_PREFIX": "/",
        "ANDROID_2_PATH_PREFIX": "/",
        "ANDROID_3_PATH_PREFIX": "/",
        "ANDROID_4_PATH_PREFIX": "/",
        "ANDROID_5_PATH_PREFIX": "/",
        "DEEPLINK_2_SCHEME": " ",
        "DEEPLINK_2_HOST": " ",
        "DEEPLINK_3_SCHEME": " ",
        "DEEPLINK_3_HOST": " ",
        "DEEPLINK_4_SCHEME": " ",
        "DEEPLINK_4_HOST": " ",
        "DEEPLINK_5_SCHEME": " ",
        "DEEPLINK_5_HOST": " "
      },
      "parse-push-plugin": {}
    },
    "platforms": [
      "browser",
      "android"
    ]
  }
}
```

**Comment by paulstelzer** [comment]
There is already an issue for that -> #15438

**Comment by brandyscarney** [comment]
Closing as duplicate of https://github.com/ionic-team/ionic/issues/15438
