### ISSUE TITLE
$event.stopPropagation() dosen't work in Ionic 2.0.0 ~ 3.5.3

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic#12480]
**Ionic Version:**
[ ] 2.0.0~3.5.3

**Type**
[ ] bug

**Platform**
[ ] all

**Current Behavior**
[ ] I create a div tag and add a tap event without it , and then create a button tag under this div and add a tap event without it . Triggering events on the button also triggers events on the div , but $event.stopPropagation() doesn't work ( In the tap event ) .

**Expected Behavior**
[ ] $event.stopPropagation() will be work, and the div event dosen't trigger when triggering the button event .

**Related Code:**
[ ] html
```
<div class="father" (tap)="hello()">
    <p>Hello</p>
    <button class="children" (tap)="say($event)">Say</button>
</div>
```
[ ] ts
```
export class FatherChildrenComponent {
    hello(): void {
        alert("hello, my children");
    }
    say(e: any): void {
        e.stopPropagation();  //$event.stopPropagation() dosen't work
        alert("father , I love you");
    }
}
```

**Error Info**
```
MapPage.html:81 ERROR TypeError: e.stopPropagation is not a function
    at MapPage.webpackJsonp.104.MapPage.unSelectedModule (map.ts:68)
    at Object.eval [as handleEvent] (MapPage.html:81)
    at handleEvent (core.es5.js:11914)
    at callWithDebugContext (core.es5.js:13206)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12794)
    at dispatchEvent (core.es5.js:8814)
    at core.es5.js:9406
    at platform-browser.es5.js:2687
    at platform-browser.es5.js:3220
    at t.invoke (polyfills.js:3)
```
**Other Info**
[ ] If you use Angular2 alone , $event.stopPropagation() will be work .

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us, we will look into this.

**Comment by YoungJoway** [comment]
@jgw96 Hello, I try the click event, $event.stopPropagation() will be work, but $event.stopPropagation() dosen't work in the tap event .

**Comment by GabrielBB** [comment]
I'm having this problem :( I hope you guys make the stopPropagation work with the tap. Sometimes we really need this

**Comment by IvanLencina** [comment]
Any solution for this?

**Comment by josejaner** [comment]
?

**Comment by Eraldo** [comment]
Also looking for a solution to this.

**Comment by hsouna** [comment]
any solution yet ?
