### ISSUE TITLE
[v4.0.0-beta.12] Angular 7 + Typescript 3.1.1

### ISSUE THREAD

**Issue by paulstelzer** [ionic-team/ionic#15810]
At the moment Ionic 4 isn't working with  Angular 7 + Typescript 3.1.1, BUT there are just 2 issues in summary.

**1. Interface 'xyz' cannot simultaneously extend types 'xyz' and 'HTMLStencilElement'. Named property 'focus' of types 'xyz' and 'HTMLStencilElement' are not identical.**

xyz are HTMLIonInputElement, HTMLIonSearchbarElement, HTMLIonTextareaElement

_Fix: I don't know if this is good practice, but if you remove 'focus': () => void in components.d.ts , this issue is fixed_

**2. Type `'Required<xyz>' `does not satisfy the constraint** 

xyz are HTMLIonModalElement and HTMLIonPopoverElement

I think it would be a great benefit if Ionc 4 would support Angular 7 from the beginning and they are already at rc.0, so I think it would make sense :)

The complete error log:

```
ERROR in node_modules/@ionic/core/dist/types/components.d.ts(5625,13): error TS2320: Interface 'HTMLIonInputElement' cannot simultaneously extend types 'IonInput' and 'HTMLStencilElement'.
  Named property 'focus' of types 'IonInput' and 'HTMLStencilElement' are not identical.
node_modules/@ionic/core/dist/types/components.d.ts(5871,13): error TS2320: Interface 'HTMLIonSearchbarElement' cannot simultaneously extend types 'IonSearchbar' and 'HTMLStencilElement'.
  Named property 'focus' of types 'IonSearchbar' and 'HTMLStencilElement' are not identical.
node_modules/@ionic/core/dist/types/components.d.ts(5967,13): error TS2320: Interface 'HTMLIonTextareaElement' cannot simultaneously extend types 'IonTextarea' and 'HTMLStencilElement'.
  Named property 'focus' of types 'IonTextarea' and 'HTMLStencilElement' are not identical.
node_modules/@ionic/core/dist/types/utils/overlays-interface.d.ts(37,52): error TS2344: Type 'Required<HTMLIonModalElement>' does not satisfy the constraint 'Required<ModalOptions<ComponentRef>>'.
  Types of property 'componentProps' are incompatible.
    Type 'unknown' is not assignable to type '{ [key: string]: any; }'.
node_modules/@ionic/core/dist/types/utils/overlays-interface.d.ts(37,288): error TS2344: Type 'Required<HTMLIonPopoverElement>' does not satisfy the constraint 'Required<PopoverOptions<ComponentRef>>'.
  Types of property 'componentProps' are incompatible.
    Type 'unknown' is not assignable to type '{ [key: string]: any; }'.
```

**Comment by NightkingCH** [comment]
Hi there

I got the same error and I'm wondering where I can find the fix or where it was applied? Can't see any code changes or pull-requests. Would like to move on with a local temporary fix until it's released.

Thanks you in advance for any informations!

**Comment by paulstelzer** [comment]
It's already fixed and will be available in next beta - the commit -> https://github.com/ionic-team/ionic/commit/5560dcd71318289081f7a14120b63708c251524e
