### ISSUE TITLE
[4.0.0-beta.5] Cannot close modal 'overlay does not exist'

### ISSUE THREAD

**Issue by doender** [ionic-team/ionic#15349]
After updating to Ionic 4.0.0-beta.5, I get the following error when calling `dismiss()` on a `ModalController` when I click on a button:
```
console.js:35 Error: Uncaught (in promise): overlay does not exist
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at 
```

Closing the modal through the backdrop works normally.

**Comment by woodstream** [comment]
How do you use it in ts file? I have found the same problem in PopoverController when use 'this.popoverController.dismiss()'，but use popover which create by PopoverController, popover.dismiss() works well.

**Comment by doender** [comment]
@woodstream Indeed, I have found the same in the case of modal overlays:

This works (within the component launched as a modal):
```
constructor(private ctrl: ModalController) {}

public async close() {
   const modal = await this.ctrl.getTop();
   modal.dismiss();
 }
```

but this doesn't:
```
constructor(private ctrl: ModalController) {}

public close() {
   this.ctrl.dismiss();
 }
```

whereas the latter used to work in the previous version.

**Comment by abennouna** [comment]
https://beta.ionicframework.com/docs/building/migration#overlay-components

**Comment by goelectricstations** [comment]
same issue too

**Comment by doender** [comment]
@abennouna I have read this; this is not the problem. My code used to work in Ionic 4.0.0-beta.4 and is documented here: https://beta.ionicframework.com/docs/api/modal-controller

**Comment by HoverBaum** [comment]
@woodstream helped us solve this by altering the code creating the modal to:

```
const modal = await this.modalCtrl.create({
      component: SliderComponent,
    });
    modal.componentProps.modal = modal;
    modal.present();
```

And then in the modal:

```
...
@Input() modal: any;
...
// in some function triggered through click.
this.modal.dismiss();
...
```

**Comment by ptitjes** [comment]
@HoverBaum, that really feels like a hack... :/

**Comment by bleuscyther** [comment]
I guess it hs to do with that: https://github.com/ionic-team/ionic/commit/c1c5102 

from the release note (https://github.com/ionic-team/ionic/releases)

Adding an **id** to the parrams fixes it but the documentation does not mention what these parameters do (data, role, id ), i only know that you can pass data to the parent using data: 

```` typescript
  this.modalController.dismiss(null, undefined, 1);
````

`...  'dismiss': (data?: any, role?: string | undefined) => Promise<void>; ...`

**Comment by pyboosted** [comment]
@bleuscyther if we pass `1` as the last argument, it works only for the first dismissing. We can write something like:

```
this.modalController.dismiss(null, undefined, null);
``` 

it would work. But still looks like bug.

**Comment by goelectricstations** [comment]
I think this is a bug that should be fix without workaround

**Comment by bleuscyther** [comment]
@goelectricstations true, what i think is happening is that the default value for id is not good. I could propose a pull request but i would like to understand what role and id do.

**Comment by HoverBaum** [comment]
@ptitjes yeah that solution is a hack around.

Looking forward to a real fix for this 🙂

**Comment by nikmartin** [comment]
@manucorporat I just updated to "@ionic/angular": "^4.0.0-beta.11", and this problem just surfaced today. is this a regression?

**Comment by peterpeterparker** [comment]
@nikmartin I've upgraded to beta-11 too, don't face any regressions regarding this

**Comment by nikmartin** [comment]
@peterpeterparker : Two things happened when I updated this morning. First, any page in my app that uses a modal controller, that modal gets loaded when the page loads. As in, I see the modal briefly as the calling page loads. This causes several errors, because route params expected by the moidal are missing. When the main page loads the modal, it loads fine, route params are passed as written, but closing the modal gives this error:
```
ERROR Error: Uncaught (in promise): overlay does not exist
    at resolvePromise (zone.js:814)
    at zone.js:724
    at rejected (main.js:1121)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:3824)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3815)

```.

The modal is loaded this way:

```
const modal = await this.modalCtrl.create({
      component: ConfirmPage,
      cssClass: 'nofull-modal',
      componentProps: {
        order: this.order,
        addtlData: addtlData,
      },
    });
    await modal.present();
```
and in the modal:

```
async dismiss(isConfirmed) {
    await this.modalCtrl.dismiss({ confirmed: isConfirmed }, undefined);
  }
```

**Comment by peterpeterparker** [comment]
@nikmartin the only difference I see is that I don't specify the 2nd parameter in dismiss

you do

     await this.modalCtrl.dismiss({ confirmed: isConfirmed }, undefined);

I do

    await this.modalCtrl.dismiss({ confirmed: isConfirmed });

otherwise don't know. Have you check that it's effectively beta.11 which is installed and not an older one (like a old hash in package-lock or something while installing)?

**Comment by bleuscyther** [comment]
I remember having this issue.

@nikhildev check your routing file to see if the route to your modal **page** was not added automatically.

Also in the module file the `ConfirmPage`  should only be in the **entryComponents** and **declarations** of the module where you use the modal.
In my terminale there was a compiling error that i had to fix first.

**Comment by peterpeterparker** [comment]
@nikmartin the source code of your app is public? like I said above it still works fine for me, I could open/close etc. modals in beta.11 no problemo
